"""initial

Revision ID: 3787dc10ce6b
Revises: 
Create Date: 2026-04-19 21:42:18.625662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3787dc10ce6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('party', sa.String(length=50), nullable=False),
    sa.Column('party_number', sa.SmallInteger(), nullable=True),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('credibility_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('source_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scraper_type', sa.String(length=50), nullable=False),
    sa.Column('scraper_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('aggregation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('aggregated_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poll_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_type', 'round', 'candidate_id', name='uq_agg_election_round_candidate')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('poll_date', sa.Date(), nullable=False),
    sa.Column('fieldwork_start', sa.Date(), nullable=True),
    sa.Column('fieldwork_end', sa.Date(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('margin_of_error', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('methodology', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_data_url', sa.String(length=1000), nullable=True),
    sa.Column('tse_registered', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institute_id', 'poll_date', 'election_type', 'round', name='uq_poll_institute_date_type_round')
    )
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('polls_found', sa.Integer(), nullable=False),
    sa.Column('polls_imported', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margin_of_error', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_spontaneous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'candidate_id', 'is_spontaneous', name='uq_result_poll_candidate_spontaneous')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_results')
    op.drop_table('scraper_runs')
    op.drop_table('polls')
    op.drop_table('aggregation_cache')
    op.drop_table('institutes')
    op.drop_table('candidates')
    # ### end Alembic commands ###
